version: '3.9'

volumes:
  postgres_data:


services:
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: devops
      DB_SCHEMA: public
      DB_PASSWORD: devops
      KEYCLOAK_USER: devops
      KEYCLOAK_PASSWORD: devops
    ports:
      - "8001:8080"


  postgres:
    build:
      context: ./.docker/postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      - POSTGRES_PASSWORD=devops
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data