basePath: /api
definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.Reservation:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      end_date:
        type: string
      id:
        type: integer
      price:
        type: number
      room:
        $ref: '#/definitions/models.Room'
      room_id:
        type: integer
      start_date:
        type: string
      total:
        type: number
      updatedAt:
        type: string
      user:
        $ref: '#/definitions/models.User'
      user_id:
        type: integer
    type: object
  models.Review:
    properties:
      comment:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      rating:
        type: integer
      reservation:
        $ref: '#/definitions/models.Reservation'
      reservationID:
        type: integer
      updatedAt:
        type: string
    type: object
  models.Room:
    properties:
      address:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      has_air_con:
        type: boolean
      has_heating:
        type: boolean
      has_internet:
        type: boolean
      has_kitchen:
        type: boolean
      has_tv:
        type: boolean
      home_type:
        type: string
      id:
        type: integer
      latitude:
        type: number
      longitude:
        type: number
      price:
        type: number
      published_at:
        type: string
      reservation:
        items:
          $ref: '#/definitions/models.Reservation'
        type: array
      room_type:
        type: string
      summary:
        type: string
      total_bedrooms:
        type: integer
      total_occupancy:
        type: integer
      updatedAt:
        type: string
      user:
        $ref: '#/definitions/models.User'
      userID:
        type: integer
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      details:
        $ref: '#/definitions/models.UserDetails'
      email:
        type: string
      emailVerifiedAt:
        type: string
      id:
        type: integer
      reservations:
        items:
          $ref: '#/definitions/models.Reservation'
        type: array
      rooms:
        items:
          $ref: '#/definitions/models.Room'
        type: array
      updatedAt:
        type: string
      username:
        type: string
    type: object
  models.UserDetails:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      description:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      phone_number:
        type: string
      profile_image:
        type: string
      remember_token:
        type: string
      updatedAt:
        type: string
      user_id:
        type: integer
    type: object
host: localhost:8000
info:
  contact:
    email: me@marclabs.com
    name: API Support
    url: http://www.swagger.io/support
  description: API for House Rent
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Stuble API
  version: "1.0"
paths:
  /reservation/update/:id:
    patch:
      description: Responds with the Updated Reservation as JSON.
      parameters:
      - description: Reservation JSON
        in: body
        name: reservation
        required: true
        schema:
          $ref: '#/definitions/models.Reservation'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Reservation'
      summary: Update Reservation object
      tags:
      - reservations
  /reservations:
    get:
      description: Responds with the list of all or filtered reservations as JSON.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Reservation'
            type: array
      summary: Get reservations list
      tags:
      - reservations
  /reservations/create:
    put:
      description: Responds with the created reservation as JSON.
      parameters:
      - description: Reservation JSON
        in: body
        name: reservation
        required: true
        schema:
          $ref: '#/definitions/models.Reservation'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Reservation'
      summary: Create reservation object
      tags:
      - reservations
  /reservations/delete:
    delete:
      description: Responds with the created reservation as JSON.
      parameters:
      - description: Reservation ID
        in: body
        name: ID
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Reservation'
      summary: Destroy reservation array
      tags:
      - reservations
  /reviews:
    get:
      description: Responds with the list of all reviews as JSON.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Review'
            type: array
      summary: Get reviews array
      tags:
      - reviews
  /reviews/create:
    put:
      description: Responds with the created review as JSON.
      parameters:
      - description: Review JSON
        in: body
        name: review
        required: true
        schema:
          $ref: '#/definitions/models.Review'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Review'
      summary: Create review object
      tags:
      - reviews
  /reviews/delete:
    delete:
      description: Responds with the created review as JSON.
      parameters:
      - description: Review ID
        in: body
        name: ID
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Review'
      summary: Destroy review array
      tags:
      - reviews
  /reviews/update/:id:
    patch:
      description: Responds with the Updated review as JSON.
      parameters:
      - description: Review JSON
        in: body
        name: review
        required: true
        schema:
          $ref: '#/definitions/models.Review'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Review'
      summary: Update review object
      tags:
      - reviews
  /rooms:
    get:
      description: Responds with the list of all rooms as JSON.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Room'
            type: array
      summary: Get rooms array
      tags:
      - rooms
  /rooms/create:
    put:
      description: Responds with the created room as JSON.
      parameters:
      - description: Room JSON
        in: body
        name: room
        required: true
        schema:
          $ref: '#/definitions/models.Room'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Room'
      summary: Create room object
      tags:
      - rooms
  /rooms/delete:
    delete:
      description: Responds with the created room as JSON.
      parameters:
      - description: Room ID
        in: body
        name: ID
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Room'
      summary: Destroy room array
      tags:
      - rooms
  /rooms/update/:id:
    patch:
      description: Responds with the Updated room as JSON.
      parameters:
      - description: Room JSON
        in: body
        name: room
        required: true
        schema:
          $ref: '#/definitions/models.Room'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Room'
      summary: Update room object
      tags:
      - rooms
  /user/details/update/:id:
    patch:
      description: Responds with the Updated detail as JSON.
      parameters:
      - description: UserDetails JSON
        in: body
        name: detail
        required: true
        schema:
          $ref: '#/definitions/models.UserDetails'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserDetails'
      summary: Update detail object
      tags:
      - details
  /users:
    get:
      description: Responds with the list of all users as JSON.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
      summary: Get users array
      tags:
      - users
  /users/create:
    put:
      description: Responds with the created user as JSON.
      parameters:
      - description: User JSON
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Create user object
      tags:
      - users
  /users/delete:
    delete:
      description: Responds with the created user as JSON.
      parameters:
      - description: User ID
        in: body
        name: ID
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Destroy user array
      tags:
      - users
  /users/details:
    get:
      description: Responds with the list of all details as JSON.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.UserDetails'
            type: array
      summary: Get details array
      tags:
      - details
  /users/details/create:
    put:
      description: Responds with the created detail as JSON.
      parameters:
      - description: UserDetails JSON
        in: body
        name: detail
        required: true
        schema:
          $ref: '#/definitions/models.UserDetails'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserDetails'
      summary: Create detail object
      tags:
      - details
  /users/details/delete:
    delete:
      description: Responds with the created detail as JSON.
      parameters:
      - description: UserDetails ID
        in: body
        name: ID
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserDetails'
      summary: Destroy detail array
      tags:
      - details
  /users/update/:id:
    patch:
      description: Responds with the Updated user as JSON.
      parameters:
      - description: User JSON
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: Update user object
      tags:
      - users
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
